language: objective-c
script:
  - xctool -workspace SignalRClientObjC.xcworkspace -scheme SignalRClientObjC -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace SignalRClientObjC.xcworkspace -scheme SignalRClientObjCTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
